name: dvhcvn
version: 2.1.20250301
description: "Three tiers of Vietnam's administrative units (last update: 01/03/2025)"
homepage: https://github.com/daohoangson/dvhcvn

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  lint: ^2.3.0
  test:
