name: dvhcvn
version: 1.3.20211101
description: "Three tiers of Vietnam's administrative units (last update: 01/11/2021)"
homepage: https://github.com/daohoangson/dvhcvn

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test:
